### ISSUE TITLE
HTTP GET leaks memory (about 70KB per call) when URL can't be reached

### ISSUE THREAD

**Issue by adb-be** [JKISoftware/JKI-REST-Client#6]
The leak does not occur when the URL can be reached.
A small vi is attached that demonstrates the issue.

[JKI_RESTClient_MemLeak.zip](https://github.com/JKISoftware/JKI-REST-Client/files/2119395/JKI_RESTClient_MemLeak.zip)

**Comment by adb-be** [comment]
The problem seems to be in HTTP Request.vi.  When the LV GET.vi fails, the handle is not actually returned as there is an error on the wire.

**Comment by adb-be** [comment]
Attached is a quick and dirty patch for HTTP Request.vi (LV17) that I am using locally now.
[HTTP Request.zip](https://github.com/JKISoftware/JKI-REST-Client/files/2119775/HTTP.Request.zip)

**Comment by jimkring** [comment]
Hi there. I tried running this in LabVIEW 2018 and I don't see any memory leak (I don't see memory usage actually going up).

I do see the code change/suggestion you're making for HTTP Request and I agree that it should call Return Client Handle, regardless of upstream error.

**Comment by adb-be** [comment]
Hi Jim,
We still use LV 2017 and see the increase in both in the LV DevEnv and the build application memory size (watching Task Manager).  Actually our application (normally about 380MB) got to 3GB (and OOM) after an overnight test with the camera detached... (causing the GET to fail about once a second)
So possibly LV 2018 is better at cleaning up unreferenced handles...  :-)
Anyway, I just wanted to let you know of the issue & fix so feel free to close it when you want.
Btw. The REST client is behaving fine in all other/normal cases... :-)

**Comment by jimkring** [comment]
This should be fixed in [release 1.3.0](https://github.com/JKISoftware/JKI-REST-Client/releases/tag/1.3.0). Please download, test, and let me know how it works for you.

![image](https://user-images.githubusercontent.com/381432/42118913-e02f0740-7bbb-11e8-883d-f0034f64f08a.png)

**Comment by adb-be** [comment]
Tested and not leaking any more... 👍

**Comment by jimkring** [comment]
fantastic! thank you for reporting this and for your help in fixing+testing.
